config/routes.rb
Rails.application.routes.draw do
  resources :players, only: [:show]

  post 'search' => 'players#search', as: :player_search

end

app/models/batting.rb
class Batting < ActiveRecord::Base
  self.table_name = 'Batting'
  self.primary_keys = :playerID, :yearID, :stint

  # database column names are invalid variable names so we rename them
  alias_attribute 'double', '2B'
  alias_attribute 'triple', '3B'

  #belongs_to :player, :foreign_key => [:playerID, :yearID, :stint]
  has_one :player, :foreign_key => :playerID
  has_and_belongs_to_many :team, :class_name => 'Team'

  def add_calculated_values

  end

  def batting_average
    if self.AB.nil?
      nil
    else
      self.AB > 0 ? self.H.to_f / self.AB : 0.0
    end
  end

  def on_base_percentage
    if self.AB.nil?
      nil
    else
      self.AB > 0 ? [self.H.to_f, self.BB, self.HBP].compact.sum / [self.AB.to_f, self.BB, self.HBP, self.SF].compact.sum : 0.0
    end
  end

  def total_bases
    if self.H.nil?
      nil
    else
      self.H + self.double + 2 * self.triple + 3 * self.HR
    end
  end

  def slugging
    if self.AB.nil?
      nil
    else
      tb = total_bases
      puts tb
     tb / self.AB
    end
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  self.table_name = 'Master'
  self.primary_key = 'playerID'

  has_many :batting, :class_name => 'Batting', :foreign_key => [:playerID, :yearID, :stint]

  BATS = { 'L' => 'Left', 'R' => 'Right', 'B' => 'Both' }
  THROWS = { 'L' => 'Left', 'R' => 'Right' }

  def self.search(search_nameFirst, search_nameLast)
    return scoped unless search_nameFirst.present? || search_nameLast.present?
    where(['nameFirst LIKE ? AND nameLast LIKE ?', "%#{search_nameFirst}%", "%#{search_nameLast}%"])
  end

  def to_s
    [nameFirst, nameLast].join(' ')
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  self.table_name = 'Teams'
  self.primary_keys = [:yearID, :lgID, :teamID]

  has_and_belongs_to_many :batting, :class_name => 'Batting' #, :foreign_key => [:battingID, :yearID, :teamID]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def show
    @player = Player.find(params[:id])
    @batting = Batting.where(playerID: params[:id])
#    @team = Team.where(yearID: @batting.yearID, teamID: @batting.teamID, lgID: @batting.lgID)
#    sql = "SELECT b.*, t.name FROM Batting b JOIN Teams t ON t.yearID = b.yearID AND t.teamID = b.teamID AND t.lgID = b.lgID WHERE b.playerID = '#{params[:id]}' "
#    @batting = ActiveRecord::Base.connection.select_all(sql).to_hash
  end

  def search
    @players = Player.search(params[:nameFirst], params[:nameLast]).all
  end

  helper :all
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
  def birth_date_formatter(player)
    if player.birthYear.nil?
      "<unknown>"
    elsif player.birthMonth.nil? || player.birthDay.nil?
      player.birthYear.to_s
    else
      "#{player.birthMonth}/#{player.birthDay}/#{player.birthYear}"
    end
  end

  def death_date_formatter(player)
    if player.birthYear.nil?
      ""
    elsif player.deathMonth.nil? || player.deathDay.nil?
      player.deathYear.to_s
    else
      "#{player.deathMonth}/#{player.deathDay}/#{player.deathYear}"
    end
  end

  def decimal_display(value)
    if value.nil?
      ""
    else
      number_with_precision(value, precision: 3)
    end
  end

  def string_date(date)
    if date.nil?
      ""
    else
      date.strftime('%m/%d/%Y')
    end

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MlbStats</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= form_tag player_search_path do %>

      <div class="center">
        First Name:
        <%= text_field_tag :nameFirst, params[:nameFirst] %>
        Last Name:
        <%= text_field_tag :nameLast, params[:nameLast] %>
      </div>
      <div class="center">
        <%= submit_tag "Search", name: nil %>
      </div>

<% end %>

</body>
</html>

app/views/players/search.html.erb
<% @players.each do |player| %>
    <%= link_to player, player_path(player, player: params[:player]) %>
<% end %>

app/views/players/show.html.erb
<html>
<head>
  <div class="center">
  <div class="player">
    <h1>
      Name: <%= @player.nameFirst %> <%= @player.nameLast %>
    </h1>
    <h4>
      <table>
        <div class="center">
        <tr>
          <td>Bats:</td>
          <td><%= Player::BATS[@player.bats] %></td>
          <td>Throws:</td>
          <td><%= Player::THROWS[@player.throws] %></td>
        </tr>
        <tr>
          <td>First Game:</td>
          <td><%= string_date(@player.debut) %></td>
        </tr>
        <tr>
          <td>Last Game:</td>
          <td><%= string_date(@player.finalGame) %></td>
        </tr>
       <tr>
          <td>Born:</td>
          <td><%= birth_date_formatter(@player) %></td>
          <td><%= @player.birthCity %></td>
          <td><%= @player.birthState %></td>
          <td><%= @player.birthCountry %></td>
        </tr>
        <tr>
          <td>Died:</td>
          <td><%= death_date_formatter(@player)  %></td>
        </tr>
      </div>
      </table>
    </h4>
  </div>

  <div class="batting">
    <h6>
      <table>
        <thead>
        <tr>
          <th>YEAR</th>
          <th>TEAM</th>
          <th>LG</th>
          <th>G</th>
          <th>AB</th>
          <th>AVG</th>
          <th>R</th>
          <th>H</th>
          <th>2B</th>
          <th>3B</th>
          <th>HR</th>
          <th>RBI</th>
          <th>SB</th>
          <th>CS</th>
          <th>BB</th>
          <th>SO</th>
          <th>IBB</th>
          <th>HBP</th>
          <th>SH</th>
          <th>SF</th>
          <th>GIDP</th>
          <th>OBP</th>
          <th>TB</th>
        </tr>
        </thead>
        <% @batting.each do |b| %>
            <tr>
              <td><%= b.yearID %></td>
              <td><%= b.teamID %></td>
              <td><%= b.lgID %></td>
              <td><%= b.G %></td>
              <td><%= b.AB %></td>
              <td><%= decimal_display(b.batting_average) %></td>
              <td><%= b.R %></td>
              <td><%= b.H %></td>
              <td><%= b.double %></td>
              <td><%= b.triple %></td>
              <td><%= b.HR %></td>
              <td><%= b.RBI %></td>
              <td><%= b.SB %></td>
              <td><%= b.CS %></td>
              <td><%= b.BB %></td>
              <td><%= b.SO %></td>
              <td><%= b.IBB %></td>
              <td><%= b.HBP %></td>
              <td><%= b.SH %></td>
              <td><%= b.SF %></td>
              <td><%= b.GIDP %></td>
              <td><%= decimal_display(b.on_base_percentage) %></td>
              <td><%= b.total_bases %></td>
            </tr>
        <% end %>
      </table>
    </h6>
  </div>
  </div>
</head>
</html>